### ISSUE TITLE
problem for data entry

### ISSUE THREAD

**Issue by jcalhinho** [IsmaelMasharo/sankey-panel#1]
hello ismael, great job for the sankey, i have a problem, i have a clickhouse database and my sql request is bad because the "required field source, target and value are missing...  

i have a csv with fieldname: ip_src, ip_dst and nb_bytes. should i replace the fieldname by alias source, target, value? 
do you have an example of request sql?

Thanks a lot

**Comment by IsmaelMasharo** [comment]
Hey @jcalhinho, you're right, the expected fields for the plugin to work are **_source_** (source nodes), **_target_** (target nodes) and **_value_** (link values). Each record in the SQL should have these 3 fields. Also, this is an acyclic network implementation of the Sankey, so loops are not allowed.

I will soon expand the docs with more details 🙏

**Comment by jcalhinho** [comment]
thanks for the answer ismael so this sql request is bad? 
SELECT  $timeSeries as t,
ip_src as source,
ip_dst as target,
nb_bytes as value,
count()
FROM $table
WHERE $timeFilter 

GROUP BY  t,source,target
ORDER BY t,value

**Comment by jcalhinho** [comment]
for me it doesn t work...

**Comment by jcalhinho** [comment]
update, after many try, it s ok with this sql: 
SELECT
    ip_src as source,
    ip_dst as target,
    nb_byte as value,
    count()
FROM $table
GROUP BY source,target,value
ORDER BY value LIMIT 25 
![Screenshot_20210111_091807](https://user-images.githubusercontent.com/52510858/104158881-8f834a00-53ee-11eb-9c8f-ca844d22befa.png)



i have an error with d[2].toFixed(2) is not a function so i delete this method and it s work but when i try more than 25 for the limit
there is an error like you said : circular link ...
any idea for fix this problem? 
thanks again ismael!

**Comment by IsmaelMasharo** [comment]
Hey @jcalhinho, looking at the sql it seems that it was failing at first since the group by clause was also expecting the field _value_. Although about your final sql, Is your intention to count the number of times a source-target pair appears? or to sum up the total _nb_yte_ for each source-target pair? Remember that it's the _value_ field that should express your total aggregation, so in your sql ```count()``` by its own it's not being taken for the chart construction. Any extra field besides _source_, _target_ and _value_ won't be taken into account. So I would say the proper sql should be whether this
```sql
COUNT() as value
```
or this
```sql
SUM(nb_byte) as value
```
I would guess for the last one.

Regarding the `d(2).toFixed(2) is not a function ` error, It seems that maybe one of the fields had missing values, or maybe the _value_ field had non-numeric values. I'll add this in the docs.

For the circular link error, you could try to mask the target values with a prefix, something like this

```sql
CASE 
  WHEN ip_src = ip_dst THEN CONCAT('P-', ip_dst)
  ELSE ip_dst
END "target",
```

Hope it was helpful 🙌

**Comment by IsmaelMasharo** [comment]
One last piece of advice, you could first build the sql and display it using a regular table, this way you could double-check the values being generated by your sql.

**Comment by jcalhinho** [comment]
great i will try now, thanks a lot!
